export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const INCREMENT_EXERCISE = 'INCREMENT_EXERCISE';